### ISSUE TITLE
code input consistency

### ISSUE THREAD

**Issue by eahefnawy** [serverless-components/Function#3]
I've recently changed the website component to take `code` as an input rather than `path` to stay consistent with other components that deal with code. We should stick to this pattern imo.

code = directory that contains the code

So for the function component:

```yml
name: function

myFunction:
  component: '@serverless/function'
  inputs:
    name: my-function
    code: ./invoke
    method: get
    permissions:
      - dynamodb?read
```

would also be useful if we introduce a code component later on.
